### ISSUE TITLE
The environment variable is not imported when the JSON file is upload.

### ISSUE THREAD

**Issue by Ashadevi-21** [testmanio/homebrew-tm#119]
**Description:** 
The environment variable is not imported when the JSON file is uploaded.
TM Version  - 3.2.3, TM-CLI Version- 1.4.4
**Priority: High**
**Expected behavior:** 
The environment variable should be successfully imported when uploading the JSON file.

**Comment by Yuviak** [comment]
Issue Fixed
Tested Version: Version 3.2.5
https://jam.dev/c/7bb12e79-689e-439e-ab11-aa2baf7d1b40
