### ISSUE TITLE
API - Status code validation

### ISSUE THREAD

**Issue by arunrajgroot** [testmanio/homebrew-tm#50]
Area ->  API
New Feature -  Need status code response validation 
Describe the bug - New feature request
Version - NO
Expected behavior - Need status code response validation 
Actual behavior - Feature not available in current version
How to Reproduce? -  NO
Anything else? - NO

Note: In current testman response validation is not included.

**Comment by thamarai1414** [comment]
1. Expected code is undefined after validating the status code  

2. Status code value in string:
await expect(restResponse.status).toEqual("200");

**Comment by thamarai1414** [comment]
Tested OK 

Now status can be validated 
Tested by both valid and invalid code 
<img width="1418" alt="Screenshot 2024-06-06 at 5 36 53 PM" src="https://github.com/testmanio/homebrew-tm/assets/102300702/6c68a990-2540-4e8b-a078-a215a39a29b4">
<img width="1418" alt="Screenshot 2024-06-06 at 5 56 03 PM" src="https://github.com/testmanio/homebrew-tm/assets/102300702/dc74741e-18e8-4598-90e6-e1cd433fd2a4">
