### ISSUE TITLE
API - Json comparison - To validate the list of keys from response body

### ISSUE THREAD

**Issue by arunrajgroot** [testmanio/homebrew-tm#51]
Area ->  API
New Feature - Need to add support to  validate the list of keys from response body
Describe the bug - New feature request
Version - NO
Expected behaviour - Need  to include response validation to validate the list of keys from response body, this need to be validated inform of number of keys expected , contains, need to restrict if additional key is included as undefined.
Actual behaviour - Feature not available in current version
How to Reproduce? -  NO
Anything else? - NO

Note: In current testman response validation is not included.

**Comment by thamarai1414** [comment]
To validate the keys in response body - TO_HAVE_JSON_INSTANCE

After generating the file v - in code, it is displayed as undefined

**Comment by thamarai1414** [comment]
Tested OK
Now we can validate the keys in the response body 
Tested by valid, invalid, extra key, re-arrange the key structure, removing some keys in response 
REST_RESPONSE@restResponse.data

 await expect(utils.compareJSONInstance(response.data,{     "auth_req_id": "",     "result_delivery_mode": "",     "user_id": "",     "success": true,     "transaction_link": "",     "interval": 5,     "request_id": "",     "expires_in": 1718108160  })).toBeTruthy();
 
 
<img width="1418" alt="Screenshot 2024-06-11 at 6 34 04 PM" src="https://github.com/testmanio/homebrew-tm/assets/102300702/98b30b31-1469-4456-8305-0d69b24ce5fb">
<img width="1418" alt="Screenshot 2024-06-11 at 6 34 32 PM" src="https://github.com/testmanio/homebrew-tm/assets/102300702/b6a58638-68a8-4ebf-a5ca-4ea3ee45ca16">

**Comment by arunrajgroot** [comment]
Issue solved and Tested OK
