### ISSUE TITLE
API- Response Type check from the response body 

### ISSUE THREAD

**Issue by arunrajgroot** [testmanio/homebrew-tm#52]
Area ->  API
New Feature - Need to add support to  validate the list of keys from response body
Describe the bug - New feature request
Version - NO
Expected behaviour - Example: if a user info is fetched i want to validate the value of a particular key and if there is another key as data in list of array type value, i want to identify the data type and validate or get a particular value from the list of array
Actual behaviour - Feature not available in current version
How to Reproduce? -  NO
Anything else? - NO

Note: In current testman response validation is not included.

**Comment by thamarai1414** [comment]
This ticket has been duplicated 

https://github.com/testmanio/homebrew-tm/issues/53
