### ISSUE TITLE
API -  Need to add Key Value check  for the static and dynamic value

### ISSUE THREAD

**Issue by arunrajgroot** [testmanio/homebrew-tm#53]
Area ->  API
New Feature - Need to add validation support of the key from the response body as to check its value contains define value or undefined dynamic value.
Describe the bug - New feature request
Version - NO
Expected behaviour -  Feature not available in current version
Actual behaviour - Feature not available in current version
How to Reproduce? -  NO
Anything else? - NO

Note: In current testman response validation is not included.

**Comment by NandhaSrinivasan** [comment]
Already this feature is supported

**Comment by thamarai1414** [comment]
Tested OK 
Now We can validate the static value of the key using TO_BE_EQUAL
REST_RESPONSE@restResponse.status.{{key}} - then pass the value 

Code:
 await expect(typeof restResponse.data.result_delivery_mode == "string"  ? restResponse.data.result_delivery_mode:JSON.stringify(restResponse.data.result_delivery_mode)).toEqual("hook@poll");
 
 Tested by both valid and invalid values of the key 
 
 file:///Users/Kannan/Downloads/Eztoverify_Smoke_Automationbk/Eztoverify_Smoke_Automation/Eztoverify_Smoke_Automation/playwright-report/index.html#?testId=93b13450cf8a674e8332-da56c3c1a906aab18db4
