### ISSUE TITLE
Global variable not imported 

### ISSUE THREAD

**Issue by Nagendran1234** [testmanio/homebrew-tm#54]
Area - Funtionality
Version - 3.1.0

Description :
Global variable not imported 

Steps : 
1. Select a branch and click on export in that branch (Should have global variable decleared)
2. Select All in the components
3. Click on Export
4. Save the downloaded file
5. Switch to other branch
6. Click on import 
7. Choose the JSON downloaded JSON File
8. Select all the components and click Import

Actual behaviour:
The Global variables are not imported

Expected behaviour:
The Global variables should be imported

Impact : High

**Comment by Yuviak** [comment]
Tested OK
Tested Version: 3.2.5
The Global variables are not imported --Issue Fixed
Refer to the attached video link
https://jam.dev/c/cad2f5f4-8e92-469e-a0ec-9dbf8d188933
