### ISSUE TITLE
White screen appears if we try to switch branch without commit

### ISSUE THREAD

**Issue by Nagendran1234** [testmanio/homebrew-tm#55]
Area - Funtionality
Version - 3.1.0

Description :
White screen appears if we try to switch branch without commit

Steps :
1. Select a branch and add or edit the cases in that branch
2. Don't click commit and push 
3. Try to change branch

Actual behaviour:
Displays white screen

Expected behaviour:
The confirmation pop up should be appeared , stating to switch the branch or to commit and push 

Impact : Medium

**Comment by Yuviak** [comment]
Tested OK
White screen appears if we try to switch branch without commit --Issue Fixed
Tested Version: 3.2.5
