### ISSUE TITLE
Need support for manual update for the test case status as Passed, failed and Skipped

### ISSUE THREAD

**Issue by arunrajgroot** [testmanio/homebrew-tm#60]
Area -> Testman
New Feature - Yes
Describe the bug - NA
Version - 3.1.0
Expected behaviour - Need support for manual update of the test case status as Passed, failed and Skipped. This option will help to track the test case status for manual validation and tracking. Option to mention the Version tested as text field will be helpful to know with what version the test case is tested and updated
Actual behaviour - No support available
How to Reproduce? - NA

**Comment by Yuviak** [comment]
Tested OK
Tested Version: 3.2.5

Need support for manual update for the test case status as Passed, failed and Skipped --Issue Fixed
https://jam.dev/c/e762b12e-e354-47f6-837f-31c1f00d6de6

**Comment by arunrajgroot** [comment]
Issue fixed and Tested ok
