### ISSUE TITLE
The comments gets disappeared

### ISSUE THREAD

**Issue by grootantest** [testmanio/homebrew-tm#61]
Area -> Comments Section
New Feature - No

Version - 4.1.0
Describe the bug
Steps :

Create 2 test cases
In first test case write a steps in comments
Now change the steps , i.e from go to url to click
Now just open the 2nd case and open 1st case again
The comments will get disappeared
Please refer the video attached
https://jam.dev/c/1a797fcf-a881-4552-a3eb-f0e48497a1fd

Expected behaviour - The commends shouldn't get deleted

**Comment by NandhaSrinivasan** [comment]
Fixed in 3.2.0-debug.2
