### ISSUE TITLE
Before all - Files gets missed while importing 

### ISSUE THREAD

**Issue by grootantest** [testmanio/homebrew-tm#62]
Area -> Comments Section
New Feature - No

Version - 3.2.0-debug.2
Files gets missed while importing before all

https://jam.dev/c/4b87c6a3-09c2-479c-9971-68f7ba48b8ad

**Comment by Yuviak** [comment]
Tested OK
Tested Version: 3.2.5
Import Before all cases gets displayed 

https://jam.dev/c/54363a66-5bad-40c5-baa7-39e732932e68
