### ISSUE TITLE
Need Copy button in preconditions

### ISSUE THREAD

**Issue by grootantest** [testmanio/homebrew-tm#63]
Area -> Comments Section
New Feature - Yes

Version - 3.2.0-debug.2

Need Copy button in preconditions (beforeAll , Beforeeach, before each, afterall)

**Comment by Yuviak** [comment]
Tested OK
Tested Version: 3.2.5
Need Copy button in preconditions (beforeAll , Beforeeach, before each, afterall)
https://jam.dev/c/8328bb47-5635-4b4e-b569-ba15a3dd7f39
