### ISSUE TITLE
To add a test case description inside a test

### ISSUE THREAD

**Issue by PriyadharshK** [testmanio/homebrew-tm#68]
Need to include the test case description.
Ex:
test('TC_013', async ({ page, browser }) => {
test('To validate the happy flow , async ({ page, browser }) => 

or 

test('TC_013: To validate the happy flow', async ({ page, browser }) => 

Purpose: We can fetch the test case id along with the description during report generation

**Comment by NandhaSrinivasan** [comment]
Added 1.4.1-3.2.0 version
