### ISSUE TITLE
Groups are missing while generating the test cases if sub-group is same in multiple groups

### ISSUE THREAD

**Issue by thamarai1414** [testmanio/homebrew-tm#69]
Area -> Functionality
New Feature - No
Describe the bug - 
Version - NO
Expected behavior - Groups are missing while generating the test cases if sub-group is same 
Actual behavior - Groups should not missed while generating the test cases  if sub-group is same 

How to Reproduce? - 
1.Create a multiple group with sub-groups 
2.Export the collections
3.Import the collection in new branch 
4.Duplicate the groups 
5.Delete the copy text
6.Import again the same collection 
7.Now we have same sub-group name for multiple groups
8.Generate the test cases

Anything else? - NO

**Comment by NandhaSrinivasan** [comment]
Reason is that duplicate names are not allowed. We restricted the duplicate group name in 3.2.0. That should reolve the issue. For existing issues please rename the groups.
