### ISSUE TITLE
While Import JSON - Subgroups is Created for each and every cases

### ISSUE THREAD

**Issue by sathishkumar-grootan** [testmanio/homebrew-tm#76]
Area -> Import and Export section
New Feature -> No
Version 3.2.1 (3.2.1)

"When exporting the JSON and attempting to import it, Each and every cases are categorized into subgroups

**Steps to Reproduce:**
1)Open the Testman
2)Switch to any branch
3)Now export the testcases as JSON type
4)Now Import the same JSON 
5) check the Result

**Comment by Yuviak** [comment]
Tested OK
Tested Version: 3.2.5
Import is working fine
https://jam.dev/c/7bb12e79-689e-439e-ab11-aa2baf7d1b40
